services:
  debug-helper:
    image: busybox
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo/data:/data/db      
  server:
    ports:
      - 3001:3000
    image: blog-server-dev
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/.:/usr/src/app 
    container_name: blog-server-compose
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
  frontend:
    container_name: blog-frontend-compose
    image: blog-frontend-dev
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://server:3000/
    build: 
      args:
        - BACKEND_URL=http://server:3000/
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/.:/usr/src/app 
    depends_on:
      - server