version: '3.8'

services:
  app:
    #image: todo-front
    build: 
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-front-compose
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    #volumes:
    #  - ./todo-frontend/.:/usr/src/app
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-compose
    depends_on:
      - app
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo/data:/data/db      
  redis:
    image: redis
    restart: always
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile
    # volumes:
    #  - ./todo-backend/:/usr/src/app
    container_name: todo-server-compose
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - redis
      - mongo
